### ISSUE TITLE
Error Failed to parse source map

### ISSUE THREAD

**Issue by ITFaishalbadriTriatra** [abdurrahman720/react-swipeable-button#1]
![image](https://github.com/abdurrahman720/react-swipeable-button/assets/133725902/225fc2e8-47db-4de8-804b-18316a847ac3)

How to fix this, react typescript

**Comment by abdurrahman720** [comment]
@ITIqbalTriatra 

Thank you for your patience and for bringing this issue to my attention. First and foremost, I sincerely apologize for the delay in addressing this—it has been over three months since your report, and as the sole active maintainer, I unfortunately missed the initial notification.

After thoroughly investigating the issue within a React TypeScript setup using a Vite project, I was unable to replicate the problem, and everything appears to be working as expected.

Could you confirm if you're using Create React App (CRA)? If so, I would highly recommend migrating to Vite as CRA has been deprecated and Vite offers a much more modern, efficient development experience. Don't forget to try the latest version v1.1.0

Looking forward to your response, and thank you again for your understanding!
